project:
  type: book
  output-dir: docs

book:
  title: "Probability And Business Statistics"
  author: "Pamela Schlosser"
  date: "4/15/2026"
  chapters:
    - index.qmd
    - introR.qmd
    - descriptives.qmd
    - dataprep.qmd
    - probability.qmd
    - ttests.qmd
    - anova.qmd
    - regression.qmd
    - summary.qmd
    - references.qmd
  navbar:
    right:
      - text: "Course Assistant"
        href: chat.html

bibliography: references.bib

format:
  html:
    css: styles.css
    number-sections: false
    include-in-header: custom-head.html
  pdf:
    documentclass: scrreprt

editor: visual
