project:
  type: book
  output-dir: docs
  resources: 
     - favicon.ico

        
book:
  title: "Probability and Business Statistics"
  author: "Pamela Schlosser"
  date: "4/15/2026"
  search: true
  chapters:
    - index.qmd
    - module1.qmd
    - module2.qmd
    - module3.qmd
    - module4.qmd
    - module5.qmd
    - module6.qmd
    - module7.qmd
    - summary.qmd
  navbar:
    right:
      - text: "Course Assistant"
        href: chat.html

format:
  html:
    css: styles.css
    number-sections: false
    include-in-header: custom-head.html
    favicon: favicon.ico
webr:
  packages:
    - ggplot2
    - dplyr
    - ISLR
    
filters:
  - webr


    
editor: source
